name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: (cd tests/corpus/schxslt-testsuite && shasum -a 256 --check SHA256SUMS)
      - run: cargo build
      - run: cargo test
      - run: cargo fmt --check
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo package --locked
      - run: cargo doc --no-deps
        env:
          RUSTDOCFLAGS: -D warnings
